travis:
  secure:
    BINSTAR_TOKEN: IP8k7HTnPFT0lQ1YvRwGfD2l6VVzaBRzFtWJxYt++Mk5NvCI4C/TcKKa9wB04Epqc0WZrK1PnbWL8dCbBzKqL6njWNL82xJ1KVSy0visC/HxOwL6CRbk8gchuNKvpTWlXAQ4sgbFV1i+5UilxRkNcw4GS8XSzRls2JaLzzFV1CoANmrWtmak6vLMFBbU1fqNqfp0iK6QGIpvzvPKW5oUI3/ShgIU+lLM0KQWD0Ngj6J2/xMInPccK3fpH/XiXssNZSbK9bRULP8dFSfAxVJNEz4ljcHxJVu9J2yJFiHWjUIzuf3NEMeLqhjIL+5DY6DcyIOfGUdJ41zLpDfVpv71ZHzAs2Beb+TeR3b6o9Kg1ppr/aP0Ca/qVib+NMfPBsUuVABDpWOW/CWQCzo4DybrmmCir2UnhmQcvs3nRWJ74Pzu4EhR2aBFIOymOKeSR26d9D45r6MS5jBIEz8EF5gYMmGYXCUaPY/Is2pyHWiRnfxQJVbELtV3zHkKHPof29LrgqDn4MPBMyq/E8YOeM55bMkWiCcXaa4TFGVjes8TCoS/60Ql4n7/nStPkD5mq49EIFib804uZL3z1qAmp/SFWZyJoPIAGaRgygghlGjxKwVjSJRbdwvbK9iNrg2Zm4g7cnmbQmgzbpJseiPjLZIKlNgyQuS9B2w0x6bo8+bEsMo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
