travis:
  secure:
    BINSTAR_TOKEN: dkHHtf6U9aAbXk+EntIDaAgDqldGKoGLEjyTl/f2nagGD7uDKIRregmMVfKqqC5GcT1hogbxRxgPmBYu3JwV3NzXIBgG03KpT4DSGBFw1S3zUhKFbHWtxZ6m/0AbpuOEXViTaHtnvWfZBAhC+IW62b+2QBp6wlkvlDTWwgHoq+iC6R02zV0IQ1gnnoQHxPn8XZmqz+Zx+9VRDOlGhLICyMuq/XdGn2AryLEI3B7ledqUJL3MfVabXqKDxJH/OFeNkIZI3yhpOrOMATrECFgRtQa7GTGP622KDAH6AaOELLLWmx86XzpKbcMFtvqfWvojgDt6lz3fu4dCnV/MGon/F4UOWlojUZSGbnZ2KrD0IaCM1du40LTpyKFIAJgI7xeZ1FfM0K9mqHZgJ9K6qxSwax9Z9lgT4O3tJR3gHhd2plE0Lqz0c9SN3W31YntGeqe0w63j4Gmok/1OBqKTJg5h6ByL/xsjfxD/ZLP+3LlvkCkicTZE5TSXg5eeHiT30tN7aU8YYCAcJ/Yys69ko1LYnzP3oGhByxk0dK0WUGM99CpwgPVa6I+BhjM2bDuL8Eb8iaGVQCUpsvpR/Ik+z8PnJgZos0lt8ugN6pDDVO/ths9txpl4IcBOC0QvOVmYox0vBTXHBwMq8AiPQgBGt7GP04S3dh/PD8dqeG40mIBbnkc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
